# Site settings
title: API Adventures
header-img: img/home-bg.jpg
email: drkeithmitchell@gmail.com
description: "People, Places, Things and the Web"
baseurl: "/apiadventures"
url: "http://apiadventures.github.io"
twitter_username: specialized
github_username:  apiadventures
facebook_username:  drkeithmitchell

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
